package model;

public enum TipoRubro {

    MEDICINA_PREPAGAa,
    VIATICOS_Y_MOVILIDAD,
    MANTENIMIENTO_DE_MUEBLES_E_INSTALACIONES,
    LIBRERIA_Y_OTROS_INSUMOS,
    PAPELERIA_E_IMPRESIONES,
    PRODUCTOS_DE_REVENTA
}



